on:
    workflow_dispatch:

jobs:
    actions-job:
        runs-on: ubuntu-latest
        steps:
            - name: Run a command in Ubuntu VM
              run: echo "This runs on the ubuntu VM"
            - name: Run inside an Alpine container
              uses: docker://alpine:3.14
              with:
                entrypoint: /bin/sh
                args: |
                  - -c
                  - echo "This runs inside an Alpine container"

            - name: Run a command in Ubuntu VM
              run: echo "This runs on the ubuntu VM"

    deckerized-job:
        runs-on: ubuntu-latest
        container: node:20
        steps:
          - run: node --version
          - run: echo "This runs inside a Node.js container"  
