# on:
#   schedule:
#     - cron: "0 0 * * *" # Minutes(0-59) Hour(0-23) Day of the month(1-31) month(1-12) day of the week(0-7) (sunday=0 or 7)

# jobs:
#   daily-task:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Print message
#         run: echo "running the scheduled task"
